services:
    db:
        image: postgres:16
        restart: always
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    chromadb:
        image: chromadb/chroma:latest
        restart: always
        volumes:
            - ./chroma_db:/data
        environment:
            IS_PERSISTENT: "TRUE"
            ANONYMIZED_TELEMETRY: "False"

    app:
        build: .
        restart: always
        env_file:
            - .env
        depends_on:
            - db
            - chromadb
        environment:
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            CHROMA_URL: http://chromadb:8000
        expose:
            - "3000"

volumes:
    postgres_data:
